version: '3.8'

services:

  person-postgres:
    image: postgres:17
    container_name: person-postgres
    environment:
      POSTGRES_DB: person
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./infrastructure/databases/person:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20
