FROM maven:3.9.11-amazoncorretto-21-debian AS builder
WORKDIR /builder
COPY target/*.jar application.jar
RUN java -Djarmode=layertools -jar application.jar extract --destination extracted

FROM maven:3.9.11-amazoncorretto-21-debian
WORKDIR /application
RUN rm -f /etc/apt/sources.list.d/corretto.list 2>/dev/null || true && apt-get update && apt-get install -y curl
COPY --from=builder /builder/extracted/dependencies/ ./
COPY --from=builder /builder/extracted/spring-boot-loader/ ./
COPY --from=builder /builder/extracted/snapshot-dependencies/ ./
COPY --from=builder /builder/extracted/application/ ./

EXPOSE 8093

ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]